name = "LeanProof"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanProof"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib.git"
rev = "3f7e94650d2fc2568ea50151af15b896f149ee96"

[[lean_lib]]
name = "LeanProof"
