name = "LeanProof"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanProof"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[require]]
name = "QIT"
git = "https://github.com/QuAIR/Lean-QIT.git"
rev = "c3d2e09be48a9dfb98abf65bc175c8609cc6ac36"

[[lean_lib]]
name = "LeanProof"
